version: "3.9"
volumes:
  psysh-store:
services:
  selloora_panel_backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    ports:
      - "8000:8000"
